### ISSUE TITLE
Add publish GitHub Action workflow

### ISSUE THREAD

**Issue by jcbhmr** [jimmywarting/whatwg-worker#8]
Automagically publishing on each GitHub Release is nice! 😎 It means you don't have to manually do `git clone`, `npm install`, and `npm publish` after you write up your release notes.

**Comment by jimmywarting** [comment]
Yea, this would be good to have. and also using semantic release:
- `fix: solve bug` makes a minor patch `0.0.x`
- `feat: added a feature` `0.x.0`
- `breaking: made something breaking change` `x.0.0`
